-- AlterTable
ALTER TABLE "Cabin" ADD COLUMN     "priceFiveNights" INTEGER NOT NULL DEFAULT 420,
ADD COLUMN     "priceFourNights" INTEGER NOT NULL DEFAULT 430,
ADD COLUMN     "priceOneNight" INTEGER NOT NULL DEFAULT 800,
ADD COLUMN     "priceSevenPlusNights" INTEGER NOT NULL DEFAULT 350,
ADD COLUMN     "priceSixNights" INTEGER NOT NULL DEFAULT 410,
ADD COLUMN     "priceThreeNights" INTEGER NOT NULL DEFAULT 440,
ADD COLUMN     "priceTwoNights" INTEGER NOT NULL DEFAULT 450,
ALTER COLUMN "pricePerNight" SET DEFAULT 450;

-- AlterTable
ALTER TABLE "Reservation" ADD COLUMN     "nights" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "pricePerNight" DECIMAL(10,2);
